{{- if .Values.createDns }}
# 🏗️ ClusterIssuer para DNS-01 Challenge usando Route53 + IRSA
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-dns
spec:
  acme:
    email: {{ required "Account email address is required!" .Values.acme.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Values.acme.secretNamePrefix }}-dns
    solvers:
      {{- range .Values.acme.solvers }}
      {{- if hasKey . "dns01" }}
      - dns01:
          {{- toYaml .dns01 | nindent 10 }}
      {{- end }}
      {{- end }}
{{- end }}
